apiVersion: apps/v1
kind: Service
metadata:
  name: mysql
  labels:
    app: wordpress
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
spec:
  selector:
	app: wordpress
	tier: mysql
  clusterIP: None
  ports:
    - port: 3306