apiVersion: v1
kind: Service
metadata:
  annotations:
    metallb.universe.tf/allow-shared-ip: shared
  name: ftps
  labels:
    app: ftps
spec:
  type: LoadBalancer
  ports:
    - port: 21
      targetPort: 21
      protocol: TCP
      name: ftps
    - port: 20
      targetPort: 20
      protocol: TCP
      name: active
    - port: 30000
      targetPort: 30000
      protocol: TCP
      name: passive-00
  selector:
    app: ftps
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ftps
  labels:
    app: ftps
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ftps
  template:
    metadata:
      labels:
        app: ftps
    spec:
      containers:
      - name: ftps
        image: ft_ftps
        imagePullPolicy: Never
        env:
        - name: USER
          valueFrom:
            secretKeyRef:
              name: ftps-secret
              key: user
        - name: PASS
          valueFrom:
            secretKeyRef:
              name: ftps-secret
              key: password
        ports:
        - containerPort: 21
          protocol: TCP
        - containerPort: 20
          protocol: TCP
        - containerPort: 30000
          protocol: TCP
