apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: influxdb
  name: influxdb
spec:
  ports:
  - port: 8086
    protocol: TCP
    targetPort: 8086
  selector:
    app: influxdb
---
apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: influxdb
  name: influxdb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: influxdb
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: influxdb
    spec:
      containers:
      - image: ft_influxdb
        name: influxdb
        imagePullPolicy: Never
        ports:
          - containerPort: 8086
        envFrom:
            - secretRef:
                name: influxdb-secret
        volumeMounts:
          - name: influx-persistent-storage
            mountPath: /var/lib/influxdb
      volumes:
      - name: influx-persistent-storage
        persistentVolumeClaim:
          claimName: influx-pv-claim
status: {}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: influxdb
  name: influx-pv-claim
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: influx-pv-volume
  labels:
    app: influxdb
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data"