apiVersion: v1
kind: Service
metadata:
  annotations:
    metallb.universe.tf/allow-shared-ip: shared
  name: telegraf
  labels:
    app: telegraf
spec:
  ports:
    - port: 4999
      protocol: UDP
      targetPort: 4999
  selector:
    app: telegraf
  type: ClusterIP
status:
  loadBalancer: {}
---
apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app: telegraf
  name: telegraf-config
data:
  telegraf.conf: |+
    [[inputs.docker]]
      endpoint = "unix:///var/run/docker.sock"
      gather_services = false
      container_names = []
      source_tag = false
      container_name_include = []
      container_name_exclude = []
      timeout = "20s"
      perdevice = true
      total = false
      docker_label_include = []
      docker_label_exclude = []
      tag_env = ["JAVA_HOME", "HEAP_SIZE"]
    [[outputs.influxdb]]
      urls = ["$INFLUXDB_URL"]
      skip_database_creation = false
      database = "$INFLUXDB_DB"
      username = "$INFLUXDB_USER"
      password = "$INFLUXDB_USER_PASSWORD"

---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: telegraf
  name: telegraf
spec:
  replicas: 1
  selector:
    matchLabels:
      app: telegraf
  template:
    metadata:
      labels:
        app: telegraf
    spec:
      containers:
        - name: telegraf
          image: ft_telegraf
          imagePullPolicy: Never
          volumeMounts:
            - mountPath: /etc/telegraf/telegraf.conf
              name: telegraf-config
              subPath: telegraf.conf
            - name: docker-socket
              mountPath: /var/run/docker.sock
          envFrom:
            - secretRef:
               name: telegraf-secret
          volumeMounts:
          - name: telegraf-config
            mountPath: etc/telegraf/telegraf.conf
            subPath: telegraf.conf
          - name: docker-socket
            mountPath: /var/run/docker.sock
      volumes:
      - name: telegraf-config
        configMap:
          name: telegraf-config
      - name: docker-socket
        hostPath:
          path: /var/run/docker.sock